//Register new user in database --Passed
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "username": "test18",
  "name": "test18",         
  "email": "khothapallirajkumar@gmail.com",
  "password": "test17@1234",  
  "gender": "other" 
}

#####
//verify user with email
GET http://localhost:3000/api/verify-email?verifyToken=9cd672dcc63a2c8f7ba16c1624239de509fccc82a9256e9ba33f2eb6e25e5aa0&userId=13

//Login user --- Passed
####
POST http://localhost:3000/api/login
Content-Type: 'application/json'

{
  "identifier": "test1",
  "password": "test1@1234"
}

//Create Contact ----- passed
####
POST http://localhost:3000/api/contacts/add-contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0MUBlbWFpbC5jb20iLCJpYXQiOjE3Mjk5NjY0ODh9.G43KBddZCPx2UVrFC1p2hRVlP0Gzh89-7902JF0qP80
Content-Type: application/json

{
    "userId": 1,
    "name" : "contact2",
    "email": "contact2@gmail.com",
    "phoneNumber": "123245678"
}

#####
//Get all contacts with the user id
GET http://localhost:3000/api/contacts/get-contacts/?userId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaWF0IjoxNzI5OTM1MDc4fQ.0uasWiC8I9NphfKqZVAl1Z-LM7i_n0R7OBk86yQb0CA

#####
//Get contact with filters
GET http://localhost:3000/api/contacts/get-filter-contacts?userId=1&name=&email=&timezone=&convertTimezone=&startDate=2024-10-24&endDate=2024-10-26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaWF0IjoxNzI5OTM1MDc4fQ.0uasWiC8I9NphfKqZVAl1Z-LM7i_n0R7OBk86yQb0CA

#####
//Update Contact --- passed
PUT http://localhost:3000/api/contacts/update-contact?userId=1&contactId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaWF0IjoxNzI5OTM1MDc4fQ.0uasWiC8I9NphfKqZVAl1Z-LM7i_n0R7OBk86yQb0CA
Content-Type: application/json

{
   "name": "contactUpdated",
   "isDeleted": false
}

#####
//Delete Contact ---- passed
DELETE http://localhost:3000/api/contacts/delete-contact?userId=1&contactId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaWF0IjoxNzI5OTM1MDc4fQ.0uasWiC8I9NphfKqZVAl1Z-LM7i_n0R7OBk86yQb0CA
